services:
  app:
    image: organization:latest
    container_name: organization
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organization.rule=Host(`organization.ramza.me`)"
      - "traefik.http.routers.organization.entrypoints=websecure"
      - "traefik.http.routers.organization.tls.certresolver=le"
      - "traefik.http.services.organization.loadbalancer.server.port=3000"
    volumes:
      - ${DATA_DIR}:/data/local.db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/data/local.db
      - WORKSPACE_TIMEZONE=${WORKSPACE_TIMEZONE}
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - proxy

networks:
  proxy:
    external: true
